### ISSUE TITLE
Server 1.19.2 ping and connection problems

### ISSUE THREAD

**Issue by Veydiz** [hypherionmc/CraterLib#13]
Hello,
In **CraterLib 2.1.0 Minecraft 1.19.2**, the mod creates major server problems. Impossible to ping it, can't even connect to it. A “HangingItem” error report would appear

**Comment by hypherionmc** [comment]
Any logs please with the full errors?

**Comment by hypherionmc** [comment]
Fix released. Thanks for reporting
