### ISSUE TITLE
Crashes on 1.20.2

### ISSUE THREAD

**Issue by Avakining** [hypherionmc/CraterLib#3]
`Mixin apply for mod craterlib failed craterlib.mixins.json:events.client.ClientLevelMixin from mod craterlib -> net.minecraft.class_638`

[craterlib-crash.log](https://github.com/firstdarkdev/CraterLib/files/12766275/craterlib-crash.log)

**Comment by hypherionmc** [comment]
Mod hasn't been ported for 1.20.2 yet, which is why it doesn't have the 1.20.2 tag on curse/modrinth. We're busy with porting still

**Comment by hypherionmc** [comment]
Update has been released
