### ISSUE TITLE
[BUG] Failed to notify Listener at playerJoinEvent

### ISSUE THREAD

**Issue by j00w33** [hypherionmc/CraterLib#4]
Versions:  
**MC**: 1.20.2
**Craterlib**: 1.0.4
**SDLink**: 3.0.0

Both Forge and Fabric affected.

**Forge Log**  
https://paste.firstdark.dev/abefulogir

**Fabric Log**  
https://paste.firstdark.dev/yemofunaka.md

**Comment by hypherionmc** [comment]
Fixed in 1.1.0
